### ISSUE TITLE
classes not autoloaded when plugin located in theme directory

### ISSUE THREAD

**Issue by montchr** [wp-shortcake/shortcake-bakery#141]
I have most of my plugins loaded from within my theme as Git submodules. This is accomplished with this code:

```php
add_filter( 'plugins_url', function( $plugins_url, $path, $plugin ){
            if ( false !== stripos( $plugin, get_template_directory() ) ) {
                $plugins_url = get_template_directory_uri() . str_replace( WP_PLUGIN_URL . get_template_directory(), '', $plugins_url );
            }
            return $plugins_url;
        }, 10, 3 );
```

However, loading it from within my theme doesn't work for this plugin. For some reason, the classes are not autoloaded. If I move the plugin to the standard WP plugins directory, everything loads fine. 

Seems that only a couple classes (not from this plugin) are passed to the autoloader at all if I dump the value of `$class`, while if I move it to plugins directory, the list of available classes is much longer.

**Comment by goldenapples** [comment]
I suspect that the problem is that you might need to instantiate the `Shortcake_Bakery` singleton manually from within your theme. The plugin tries to instantiate itself on an `after_setup_theme` hook, which will have already fired by the time it's loaded as part of your theme... and therefore won't get set up properly.

If you manually instantiate from inside your theme, by calling `Shortcake_Bakery::get_instance()` (or just `Shortcake_Bakery()`), does it work?

**Comment by montchr** [comment]
@goldenapples That did the trick, thanks!
