### ISSUE TITLE
youtube playlist id missing from embed url on frontend only

### ISSUE THREAD

**Issue by montchr** [wp-shortcake/shortcake-bakery#145]
If I add a YouTube video with a playlist ID in the URL, the shortcode text includes the full URL I supplied it, and the in-editor rendering of the `<iframe>` uses this URL and the resulting embed indicates that the video is in a playlist:

![](http://cl.montchr.io/image/3R0k1Y2o0t2B/Image%202015-11-09%20at%2012%3A48%3A49.png)

However, when I view the post on the frontend, the URL for the `<iframe>` does not include the playlist ID, and the embed treats the video as a single video:

![](http://cl.montchr.io/image/3Y0i1J2R0K2N/Image%202015-11-09%20at%2012%3A50%3A10.png)

**Comment by danielbachhuber** [comment]
Huh. Can you share the full shortcode?

**Comment by montchr** [comment]
`[youtube url="https://youtu.be/f9y9Snt1g5E?list=PL6F6DE2FF0854D7C6"]`

**Comment by danielbachhuber** [comment]
Hm. The shortcode you provided works as expected for me locally.

Are you running Jetpack? Or do you have other plugins which could be interfering?

**Comment by montchr** [comment]
I just tested on a fresh install and the issue is still happening.

**Comment by danielbachhuber** [comment]
Ok. I was able to reproduce. The problem seems to be specific to previewing a post.

When the shortcode is rendered during a preview, the passed URL is:

```
https://www.youtube.com/watch?v=f9y9Snt1g5E&#038;list=PL6F6DE2FF0854D7C6
```

When the shortcode is rendered after the post is saved and the permalink is accessed, the passed URL is:

```
https://www.youtube.com/watch?v=f9y9Snt1g5E&list=PL6F6DE2FF0854D7C6
```

`parse_url()` doesn't properly handle the `#038;` encoded version of the ampersand. However, I'm not sure why it's being encoded this way.

**Comment by danielbachhuber** [comment]
:hammer:
