### ISSUE TITLE
Feature Request: Filter Available Options

### ISSUE THREAD

**Issue by mrjarbenne** [wp-shortcake/shortcake-bakery#160]
I recognize the edge-case here, so apologies. We have a K12 blogging platform. Some of the providers you are surfacing are not necessarily appropriate for our K12 audience. Is there a means of filtering the Shortcake providers (without hacking the plugin) in a way perhaps similar to what is available for Jetpack?

https://jeremy.hu/customize-the-list-of-modules-available-in-jetpack/

Thanks in advance for the consideration.

**Comment by goldenapples** [comment]
That's not really an edge-case, it's a very reasonable option to have. :)  

Also, because the shortcodes take up a considerable amount of space in the selection UI, there's no reason for a site to expose more than they actually expect their users to need.

Because all the shortcodes registered here are registered with Shortcake, you can use the `shortcode_ui_shortcodes` filter to remove the ones you don't want to use.

```
add_filter( 'shortcode_ui_shortcodes', function( $registered_shortcodes ) {
   unset( $registered_shortcodes['giphy'] );
   unset( $registered_shortcodes['infogram'] );
   return $registered_shortcodes;
}
```

Does that work for what you're trying to do?

**Comment by mrjarbenne** [comment]
That's awesome. Thanks so much. 

https://github.com/hwdsbcommons/curate-the-bakery
